---
- hosts: all
  gather_facts: False
  tasks:
      # Install software repo 
  - name: Install Software Repo
    shell: apt-get -y install software-properties-common
    sudo: true

    # Install Ansible Repo  
  - name: Install Ansible Repo
    shell: apt-add-repository -y ppa:ansible/ansible
    sudo: true

    # Update APT      
  - name: Update APT
    shell: apt-get update
    sudo: true

    # Install Ansible     
  - name: Install Ansible via NPM
    shell: apt-get -y install ansible
    sudo: true

  - name: Install python and node
    apt: pkg={{item}} state=installed
    sudo: true
    with_items:
         - python
         - python-pip
         - git
         - build-essential
         - python-dev
         - libffi-dev
         - libxml2-dev
         - libxslt1-dev
         - lib32z1-dev
         - libssl-dev
         - npm
         - nodejs

  - name: install required python dependencies
    sudo: true
    pip: requirements=/vagrant/requirements.txt executable=pip
    
    # Fix a temporary issue with PyNTC library which ntc-ansible depends on.
  - name: Fix Node vs nodejs Link - known ubuntu thing google it
    shell: ln -sf /usr/bin/nodejs /usr/bin/node
    sudo: true

  - name: Install Serverless framework
    shell: npm install -g serverless
    sudo: true
    
    # Install Loopback via root 
#  - name: Install Loopback via NPM this will take 10-20 minutes
#    shell: npm install -g strongloop
#    sudo: true

#    # Install Loopback and Node
#  - npm:
#      name: strongloop
#      global: yes
  
  
#     Clean Repo forcefully
#  - name: Clean NTC Repo
#    shell: rm -rf /usr/share/ansible/ntc-ansible
#    sudo: true

  - name: Clean NTC Repo if it exists
    file:
      state: absent
      path: "/usr/share/ansible/ntc-ansible"

    # Install NTC Repo, git module was broken at time.      
  - name: Clone NTC-Ansible
    shell: git clone https://github.com/networktocode/ntc-ansible --recursive /usr/share/ansible/ntc-ansible
    sudo: true

    # Install Ansible Spark Module, git module was broken at time.      
  - name: Clone Ansible Cisco Spark Module
    shell: sudo wget https://raw.githubusercontent.com/drew-russell/ansible/610dc9993cbcd15bf7e5e7771090debb55f1ec76/lib/ansible/modules/notification/cisco_spark.py  -O /usr/lib/python2.7/dist-packages/ansible/modules/extras/notification/cisco_spark.py
    sudo: true

    # Install Flint    
  - name: Install Flint via NPM
    shell: npm install -g node-flint
    sudo: true

    # Install Restify    
  - name: Install Restify via NPM
    shell: npm install -g restify
    sudo: true

    # Clone Code Camp Repo      
#  - name: Clone Code Camp Repo
#    shell: git clone https://github.com/jasonbarbee/TekLinksCodeCamp-Jan-2017 /home/vagrant/

# - name: Copy the repo to Vagrant
#    shell: cp -r /home/vagrant/code-camp /vagrant/code-camp
     
#  - name: Fix Ansible Config File Defaults
#    shell: cp /vagrant/Ansible/ansible.cfg /etc/ansible/ansible.cfg
#    sudo: true

  - name: Fix missing ssh known host file - ansible crashed without it
    shell: echo "" >> /home/vagrant/.ssh/known_hosts
    sudo: true
  - name: Fix missing ssh known host file - ansible crashed without it
    shell: chown vagrant /home/vagrant/.ssh/known_hosts
    sudo: true 

    # Fix a temporary issue with PyNTC library which ntc-ansible depends on.
  - name: Rename NTC files 
    shell: mv /usr/share/ansible/ntc-ansible/setup.py /usr/share/ansible/ntc-ansible/oldsetup.py
    sudo: true

    # Fix a temporary issue with PyNTC library which ntc-ansible depends on.
  - name: Rename NTC files 
    shell: mv /usr/share/ansible/ntc-ansible/setup.cfg /usr/share/ansible/ntc-ansible/oldsetup.cfg
    sudo: true

    # Fix a temporary issue with PyNTC library which ntc-ansible depends on.
  - name: Rename NTC files 
    shell: mv /usr/share/ansible/ntc-ansible/ntc-templates/setup.py /usr/share/ansible/ntc-ansible/ntc-templates/oldsetup.py
    sudo: true




