---
    - name: Security Alert
      shell: echo "SECURITY ALERT!"
    - name: Alert the NOC Team
      uri:
        url: "https://hook.io/{{ hookname }}/securitycheck?bottoken={{ bottoken }}&hookname={{ hookname }}&version={{ result.ansible_facts.ansible_net_version }}&hostname={{ result.ansible_facts.ansible_net_hostname }}&roomid={{ roomid }}"
        method: GET
