---
- name: VyOS Show Commands
  hosts: all
  connection: local

  vars:
    version: ""
    ansible_net_version: ""
    cli:
      host: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      transport: cli


  tasks:
    - name: collect all facts from the device
      vyos_facts:
        gather_subset: all
        provider: "{{ cli }}"
      register: result

    - name: debug stuff
      debug:
        var: result.ansible_facts

    - include: security-alert.yml
      when: result.ansible_facts.ansible_net_version == "VyOS"

    - name: Show version
      vyos_command:
        commands:
          - show version
        provider: "{{ cli }}"

    - name: configure the remote device
      vyos_config:
        backup: yes
        lines:
          - set system host-name AWS-CodeCamp
        provider: "{{ cli }}"

    - name: backup and load from file
      vyos_config:
        src: vyos.cfg
        backup: yes
        provider: "{{ cli }}"
