---
    - name: Alert the NOC Team about rogue VyOS
      uri:
        url: "https://hook.io/{{ hookname }}/securityalert"
        method: POST
        HEADER_Content-Type: application/json
        body: '{{ post|to_json }}'
        body_format: json
        validate_certs: no
        status_code: 200
        return_content: yes
