---
- name: VyOS Show Commands
  hosts: all
  connection: local

  vars:
    post:
      bottoken : "{{ bottoken }}"
      hookname : "{{ hookname }}"
      ip : "{{ inventory_hostname }}"
      version : "{{ result.ansible_facts.ansible_net_version }}"
      hostname : "{{ result.ansible_facts.ansible_net_hostname  }}"
      roomid : "{{ roomid }}"
      numbertocall : "{{ numbertocall }}" 
      customername : "{{ customername }}"
      tropotoken : "{{ tropotoken }}"
    version: ""
    ansible_net_version: ""
    cli:
      host: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      transport: cli


  tasks:
    - name: collect all facts from the device
      vyos_facts:
        gather_subset: all
        provider: "{{ cli }}"
      register: result

    - name: debug stuff
      debug:
        var: result.ansible_facts

    - include: security-alert.yml
      when: result.ansible_facts.ansible_net_version == "VyOS"

    - name: Show version
      vyos_command:
        commands:
          - show version
        provider: "{{ cli }}"
